apiVersion: v1
kind: Service
metadata:
  name: koach
  namespace: kube-system
spec:
  selector:
    kubearmor-app: kubearmor-koach
  ports:
  - port: 3001
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: koach
  namespace: kube-system
  labels:
    kubearmor-app: kubearmor-koach
spec:
  replicas: 1
  selector:
    matchLabels:
      kubearmor-app: kubearmor-koach
  template:
    metadata:
      labels:
        kubearmor-app: kubearmor-koach
      annotations:
        kubearmor-policy: audited
    spec:
      serviceAccountName: kubearmor
      containers:
      - name: kubearmor-koach
        image: nathanieljason/koach-test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
            